### PR TITLE
feat: support using podman instead of docker

### PR DESCRIPTION
**Pull request by Otterpohl**

### CODE REVIEW

**Review by gbartolini — APPROVED** [review]

**Comment by gbartolini** [comment]
I checked it doesn't break my Docker setup. @sxd could you please verify it works with podman?

**Comment by sxd** [comment]
@gbartolini sure! :)

**Comment by sxd** [comment]
Hi @Otterpohl 

This change requires some modifications in the systemd layer right? Can you add some documentation about it?

Also, I was checking the code and what do you think about something like this:
```shell
for containerProvider in `which docker podman`; do
    CONTAINER_PROVIDER=$containerProvider
    break
done
```
Instead of trying to replace or add functions we just use the first one we found, and since we know that podman has the same command line and syntax as docker it should be a problem to use something like
```shell
$CONTAINER_PROVIDER run ...
```

Let me know what do you think!

Regards,

**Comment by Otterpohl** [comment]
@sxd I didn't do any changes to systemd (I am running this on a Mac) 
What did you have to do to get it working?

I do much prefer your method, updated it now.

Note:
I have added checking for the container provider in `teardown.sh` otherwise `docker rm ...` turns into `rm ...`

**Comment by sxd** [comment]
Wow!! nice work @Otterpohl 

This is what was required on GNU/Linux https://kind.sigs.k8s.io/docs/user/rootless/ probably we can link people to that if they get the error, I will try to emulate again when I have some time later today.

Another suggestions, what if we create a lib so we can use that lib from both scripts? so we have only one functions to call from both scripts, that will be a really nice improvement! If you don't have time it's ok this way! 

I'm going to tests these changes and will let you know but for sure we merge this soon! :D 

Regards!

**Comment by sxd** [comment]
Hi @Otterpohl and @gbartolini 

The only way to create a kind cluster using podman in GNU/Linux with Kernel 6.11 (yes to make sure we don't have cgroup v1) is using the following command:

```shell
systemd-run --scope --user -p "Delegate=yes" kind create cluster
```

This will create a cluster at least in Debian flavor distributions, sadly, there's another option that it's handled in this documentation https://kind.sigs.k8s.io/docs/user/rootless/#host-requirements.

As is stated in the kind documentation https://kind.sigs.k8s.io/docs/user/rootless/#creating-a-kind-cluster-with-rootless-podman the podman support is experimental, but that's ok with my, I think that if we state in the documentation that podman will work in macOS and to make it work in GNU/Linux you need to do some changes, we could merge this.

@gbartolini thoughts ?

Regards,

**Review by leonardoce — APPROVED** [review]

**Pull request merged**
